CLASS zcl_hh_drp_event_consumption DEFINITION
  PUBLIC ABSTRACT FINAL
  CREATE PUBLIC
  FOR EVENTS OF ZHH_R_DRPCurrency.

  PUBLIC SECTION.

  PROTECTED SECTION.

  PRIVATE SECTION.

ENDCLASS.


CLASS zcl_hh_drp_event_consumption IMPLEMENTATION.
ENDCLASS.
